### ISSUE TITLE
Item 29, p89,  BoundedResistance has no attribute _ohm 

### ISSUE THREAD

**Issue by fwang2** [bslatkin/effectivepython#27]
The parent class `Resistor` has no attribute of `_ohm`, it has `ohm` defined instead.
`BoundedReistance` refers to `_ohm` nonetheless, so the example won't run as it is:

```python
class Resistor(object):
    def __init__(self, ohms):
        self.ohms - ohms
        self.voltage = 0
        self.current = 0

class BoundedResistance(Resistor):
    def __init__(self, ohms):
        super().__init__(ohms)

    @property
    def ohms(self):
        return self._ohms

    @ohms.setter
    def ohms(self, ohms):
        if ohms <= 0:
            raise ValueError
        self._ohms = ohms


r3 = BoundedResistance(1e3)
r3.ohms = 0
```

The output is:

```python
Traceback (most recent call last):
  File "attr.py", line 22, in <module>
    r3 = BoundedResistance(1e3)
  File "attr.py", line 9, in __init__
    super().__init__(ohms)
  File "attr.py", line 3, in __init__
    self.ohms - ohms
  File "attr.py", line 13, in ohms
    return self._ohms
AttributeError: 'BoundedResistance' object has no attribute '_ohms'
```

**Comment by fwang2** [comment]
typo, my bad
