### ISSUE TITLE
Return statement for Python 2 generators is possible, but only without a value

### ISSUE THREAD

**Issue by bslatkin** [bslatkin/effectivepython#3]
I say this in Item #40:

"The second limitation is that there is no support for the return statement in Python 2 generators. To get the same behavior that interacts correctly with try/except/finally blocks, you need to define your own exception type and raise it when you want to return a value."

I meant return with a value. You can do a "bare" return in Python 2 and it will do try/except/finally correctly:

```
>>> def foo():
...   try:
...     yield 1
...     return
...   finally:
...     print('hi')
... 
>>> foo()
<generator object foo at 0x10754f050>
>>> it = foo()
>>> it.next()
1
>>> it.next()
hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

**Comment by bslatkin** [comment]
But the point is, yielding a return-looking value from a generator won't run the try/except/finally blocks:

```
>>> class Return(object):
...     def __init__(self, value):
...         self.value = value
... 
>>> def foo():
...   try:
...     yield 1
...     yield Return(5)
...   finally:
...     print('hi')
... 
>>> it = foo()
>>> it.next()
1
>>> it.next()
<__main__.Return object at 0x10753de50>
>>> it.next()
hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

To get the right behavior, you need to raise an exception:

```
>>> class Return(Exception):
...     def __init__(self, value):
...         self.value = value
... 
>>> def foo():
...   try:
...     yield 1
...     raise Return(5)
...   finally:
...     print('hi')
... 
>>> it = foo()
>>> it.next()
1
>>> it.next()
hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in foo
__main__.Return
```

**Comment by bslatkin** [comment]
[Original source](http://www.reddit.com/r/Python/comments/2zhfxa/effective_python_item_40_consider_coroutines_to/cpjnx2m)

**Comment by bslatkin** [comment]
Fixed in next printing.
